version: "3.9"

services:
  message-broker:
    container_name: rabbitmq-container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=12345
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  db:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: insurance-calc-db
    ports:
      - "3000:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  insurance-calculator-app:
    container_name: insurance-calc-container
    image: insurance-calculator:1.0.3
    ports:
      - "8080:8080"
    depends_on:
      message-broker:
        condition: service_healthy
      db:
        condition: service_healthy